NOISSUE - Update Docs
ultravioletrs/cocos-docs pull request #21
Opened 2024-02-19 08:44 UTC by WashingtonKK

Signed-off-by: WashingtonKK <washingtonkigan@gmail.com>

2024-02-22 17:32 UTC, drasko requested changes

2024-02-22 17:32 UTC, drasko commented on docs/manager.md
> +## Setup and test manager <> agent
Capitalize words in titles

2024-02-22 17:32 UTC, drasko commented on docs/manager.md
> +#### Build and run Agent
Capitalize

2024-03-18 16:30 UTC, SammyOina requested changes

2024-03-18 16:30 UTC, SammyOina commented on docs/agent.md
> +## gRPC Connection Between Agent & Manager
there is no gRPC between agent and manager

2024-03-18 16:30 UTC, SammyOina commented on docs/agent.md
> +## Vsock Bonnection Between Agent & Manager
fix typo

2024-03-20 14:55 UTC, drasko approved these changes
LGTM

2024-03-20 14:56 UTC, merged