NOISSUE: Add Documentation for Running Algo with Args
ultravioletrs/cocos-docs pull request #41
Opened 2024-08-29 08:04 UTC by WashingtonKK

# What type of PR is this?

This is an enhancement since it adds documentation for running an algo that requires command line args.

## What does this do?

It adds documentation for running an algo that requires command line args.

## Which issue(s) does this PR fix/relate to?

- No issue related

## Have you included tests for your changes?

Not needed for docs.

## Did you document any new/modified features?

Yes, this adds documentation for a feature in cocos.

### Notes

2024-08-29 08:06 UTC, rodneyosodo requested changes

2024-08-29 08:06 UTC, rodneyosodo commented on docs/algorithms.md
> +Details of how to run the full addition example with args can be found [here](https://github.com/ultravioletrs/cocos/blob/7a2789fb5fda48282ef0c1d516aa8ba36421f5f1/test/manual/algo/README.md).
Port this documentation to here since this is the main documentation place

2024-08-29 08:07 UTC, SammyOina requested changes

2024-08-29 08:07 UTC, SammyOina commented on docs/algorithms.md
> +To run a python algo that requires command line arguments, you can append the algo command on cli with the arguments needed as shown in the addition example:
not only python arguments are for all algos

2024-08-29 08:07 UTC, SammyOina commented on docs/algorithms.md
> +./build/cocos-cli algo ./test/manual/algo/addition.py ./private.pem -a python --args="--a" --args="100" --args="--b" --args="20"
include more detail on how to add arguments, order, how may you need to add, show how the added args will be passed by agent to the algo

2024-09-03 20:56 UTC, SammyOina requested changes

2024-09-03 20:56 UTC, SammyOina commented on docs/algorithms.md
> +Export the agent grpc url from computation server logs, by default
this sentence sounds incomplete at the end

2024-09-03 20:56 UTC, SammyOina commented on docs/algorithms.md
> +To run an algo that requires command line arguments, you can append the algo command on cli with the arguments needed as shown in the addition example, which we will run with args below:
algorithm

2024-09-10 12:14 UTC, smithjilks approved these changes
LGTM!

2024-09-10 17:06 UTC, SammyOina requested changes

2024-09-11 08:58 UTC, SammyOina approved these changes

2024-09-11 09:16 UTC, merged