NOISSUE - Switch to docasarus
ultravioletrs/cocos-docs pull request #45
Opened 2024-12-18 13:00 UTC by SammyOina

# What type of PR is this?

## What does this do?

## Which issue(s) does this PR fix/relate to?

## Have you included tests for your changes?

## Did you document any new/modified features?

### Notes

2024-12-19 10:51 UTC, dborovcanin commented
@SammyOina Is this ready?

2024-12-19 12:13 UTC, WashingtonKK commented on README copy.md
Is this a duplicate file?

2024-12-19 16:53 UTC, dborovcanin requested changes
@SammyOina Let's remove the landing page and go directly to /intro.

2024-12-20 09:39 UTC, dborovcanin commented
@SammyOina Please completely remove blogs from the navigation.

2024-12-20 09:45 UTC, WashingtonKK requested changes
Also update instructions to run locally.

2024-12-20 09:45 UTC, WashingtonKK commented on README.md
> +$ yarn
Add npm option

2024-12-20 09:45 UTC, WashingtonKK commented on README.md
> +$ yarn start
This does not work

2024-12-20 11:01 UTC, SammyOina commented on README.md
> +$ yarn
we do not need both

2024-12-20 11:01 UTC, SammyOina commented on README.md
> +$ yarn start
check on your local deployment

2024-12-20 11:09 UTC, WashingtonKK approved these changes

2024-12-20 11:09 UTC, WashingtonKK approved these changes

2024-12-20 11:56 UTC, dborovcanin approved these changes

2024-12-20 11:57 UTC, merged